Develop update - added class to make similiar Requests in bulk
xhsun/gw2wrapper pull request #33
Opened 2017-11-07 14:45 UTC by Levvy055

in Gw2Request JavaDoc is still not updated (used ones from SynchronusRequest)
and tests not added yet.
-> That is why it is pull request to develop branch.

2017-11-08 02:28 UTC, xhsun reviewed
Since Android only supports a subset of Java 8, I prefer to leave source and target compatibility to 1.7 (for build.gradle). So that we don't accidentally introduce some feature that might not work for Android.

2017-11-08 03:13 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +		return instance;
Would it be better to inform user that the instance is already initialized? So that they know the program might not be using their custom client.

2017-11-08 03:43 UTC, xhsun requested changes
Could you review code comment I left for you?

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +	public static LanguageSelect getLang() {
Could you change the method name to getLanguage? So that it matches setLanguage

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +		return instance;
Would it be better to inform user that the instance is already initialized? So that they know the program might not be using their custom client.

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +	public GuildWars2API getGw2Api() {
I guess it doesn't really hurt to provide GuildWars2API to the user. 

However, GuildWars2API is package private, which means the user will not be able to access any method in that class without using reflection. Aaand I kinda want to keep it package private, so that the user don't get confused.

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/Gw2Request.java
> +final class Gw2Request {
Need to be public. Otherwise user cannot access any of the methods

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/SynchronousRequest.java
> +	public SynchronousRequest(GuildWars2API gw2API) {
Can you change this back to package private? I don't want the user to be able to instantiate this class without calling GuildWars2 first

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/SynchronousRequest.java
> -	public List<Integer> getAllAchievementCategoryID() throws GuildWars2Exception {
Instead of completely remove getAllAchievementCategoryID(), maybe do something similar to the following?
```java
@Deprecated
public List<Integer> getAllAchievementCategoryID() throws GuildWars2Exception {
  return getAllAchievementCategoryIDs();
}
```

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> +	public AsynchronousRequest(GuildWars2API gw2API) {
Can you change this back to package private? I don't want the user to be able to instantiate this class without calling GuildWars2 first

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> -	public void getPvPSeasonLeaderBoardInfo(String id, String type, World.Region region, Callback<List<PvPLeaderBoard>> callback) throws NullPointerException {
Instead of completely remove getPvPSeasonLeaderBoardInfo, maybe do something similar to the following?
```java
@Deprecated
public void getPvPSeasonLeaderBoardInfo(String id, String type, World.Region region, Callback<List<PvPLeaderBoard>> callback) throws NullPointerException {
  return getPvPSeasonLeaderboardInfo(id, type, region, callback);
}
```

2017-11-08 03:43 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> -	public void getGuildMemberInfo(String id, String api, Callback<List<GuildMember>> callback) throws GuildWars2Exception, NullPointerException {
Instead of completely remove getGuildMemberInfo, maybe do something similar to the following?
```java
@Deprecated
public void getGuildMemberInfo(String id, String api, Callback<List<GuildMember>> callback) throws GuildWars2Exception, NullPointerException {
  return getGuildMembersInfo(id, api, callback);
}
```

2017-11-08 03:47 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/Requester.java
> +	private static List<Requester> instances = new ArrayList<>();
I'm kinda curious. 
Why do you need to keep track of all the instances?

2017-11-08 03:54 UTC, xhsun commented
I really like you idea to merge asynchronous request and synchronous request. But I need to check if this addition will break the library in Android environment or not (since it make use of Java 8).

2017-11-08 11:14 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> +	public AsynchronousRequest(GuildWars2API gw2API) {
Ahh. Forgot to change it back. My bad.

2017-11-08 11:16 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> -	public void getGuildMemberInfo(String id, String api, Callback<List<GuildMember>> callback) throws GuildWars2Exception, NullPointerException {
I have made this change because already in SynchronousRequest is this name of the same method.

2017-11-08 11:17 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> -	public void getPvPSeasonLeaderBoardInfo(String id, String type, World.Region region, Callback<List<PvPLeaderBoard>> callback) throws NullPointerException {
Same as above comment

2017-11-08 11:18 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +		return instance;
It's for convenience, cause like me  I need to change default timeouts of requests in my project. Maybe add something like that in javadoc?

2017-11-08 11:19 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +	public static LanguageSelect getLang() {
ok

2017-11-08 11:20 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +	public GuildWars2API getGw2Api() {
It's just for advanced usage. Let me think about it.

2017-11-08 15:48 UTC, Levvy055 commented
How about: 
```
targetCompatibility = '1.7'
sourceCompatibility = '1.8'
```

2017-11-08 18:28 UTC, xhsun commented
Cannot build the artifact if source is 1.8 and target is 1.7
```
Error:java: javacTask: source release 1.8 requires target release 1.8
```

2017-11-08 18:28 UTC, xhsun commented
Cannot build the artifact if source is 1.8 and target is 1.7
```
Error:java: javacTask: source release 1.8 requires target release 1.8
```

2017-11-08 18:29 UTC, xhsun commented
Cannot build the artifact if source is 1.8 and target is 1.7
```
Error:java: javacTask: source release 1.8 requires target release 1.8
```

2017-11-08 18:49 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> -	public void getGuildMemberInfo(String id, String api, Callback<List<GuildMember>> callback) throws GuildWars2Exception, NullPointerException {
Yeah, I notice the typo. I was trying to add some backward compatibility by telling people to use the fixed version instead. Something like:

``` java
/**
*use {@link AsynchronousRequest#getGuildMembersInfo(String, String, Callback)} instead
*/
@Deprecated
public void getGuildMemberInfo(String id, String api, Callback<List<GuildMember>> callback) throws GuildWars2Exception, NullPointerException {
  return getGuildMembersInfo(id, api, callback);
}
```
I'm okay with change it without notify people in code. I can always document the change in the patch note

2017-11-08 19:01 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +		return instance;
Yeah, I know and I like your addition. 
I was trying to suggest instead of getInstance, name it setInstance. So that it is consistent with with setInstance(Cache). And since people only able to create the instance with custom client the first time they initialize the instance, it make sense to call it setInstance (I think). So something like the following:
```java
public static void setInstance(OkHttpClient client) throws GuildWars2Exception {
  if (instance != null)
    throw new GuildWars2Exception(ErrorCode.Other, "Instance already initialized");
  instance = new GuildWars2(client);
}
```

2017-11-08 21:54 UTC, Levvy055 commented
https://stackoverflow.com/a/37294741/3625851

2017-11-08 23:23 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/Requester.java
> +	private static List<Requester> instances = new ArrayList<>();
To interrupt all requests when closing app. Not done yet.

2017-11-08 23:24 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/SynchronousRequest.java
> -	public List<Integer> getAllAchievementCategoryID() throws GuildWars2Exception {
when it means All so IDs is correct plural form as it is in AsyncRequest.
If wanna have back compatibility then best it will be to add @Depracated annotation

2017-11-08 23:25 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/GuildWars2.java
> +		return instance;
ahh ok. I get it now ;)

2017-11-08 23:26 UTC, Levvy055 commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> -	public void getGuildMemberInfo(String id, String api, Callback<List<GuildMember>> callback) throws GuildWars2Exception, NullPointerException {
For that is @Depracated annotation

2017-11-09 16:25 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/AsynchronousRequest.java
> -	public void getGuildMemberInfo(String id, String api, Callback<List<GuildMember>> callback) throws GuildWars2Exception, NullPointerException {
yeah, basically add @Deprecated to the function instead of removing it completely

2017-11-09 16:26 UTC, xhsun commented on src/main/java/me/xhsun/guildwars2wrapper/request/SynchronousRequest.java
> -	public List<Integer> getAllAchievementCategoryID() throws GuildWars2Exception {
yeah, add @Deprecated please

2017-11-09 17:47 UTC, xhsun commented
Yeah, I know about those compile options. But I don't think we should force people to use it for their Android project. Since if their min SDK level is less than 24 and they are not using retrolambda or similar libraries, the compiler will not warn them about using Java 8 functions (and their code will probably crash and burn during runtime). Aaand this library doesn't exactly provide any replacement for the Java 8 functionalities. So I think it is for the best we don't force them to enable those compile options.

2018-08-18 20:25 UTC, closed without merging